# ~/raj-manghani-odyssey-resume/docker-compose.yml
# FINAL Version with Certbot auto-renewal entrypoint enabled
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: odyssey-frontend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: odyssey-backend
    environment:
      - DEPLOYMENT_MODE=docker
      - APP_ROOT_DIR=/app
    restart: unless-stopped

  proxy: # The Nginx Reverse Proxy service
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    network_mode: host # Add host network mode
    volumes:
      # Use the FINAL Nginx config with HTTPS block uncommented
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount volumes for certs and challenges (read-only for Nginx)
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_webroot:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  certbot: # Certbot Service for SSL Certificates
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      # Mount volumes for certs and challenges (read-write for Certbot)
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    # --- Entrypoint for auto-renewal is UNCOMMENTED ---
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Define named volumes at the TOP LEVEL
volumes:
  certbot_certs:
  certbot_webroot:
