# ~/raj-manghani-odyssey-resume/docker-compose.prod.yml
# Production version: Uses pre-built images from registry, no build sections.
version: '3.8' # Keep version for compatibility, though obsolete

services:
  frontend:
    # Removed build section
    image: ${REGISTRY_URL:-docker.io/rajmanghani}/${FRONTEND_IMAGE_NAME:-raj-manghani-odyssey-frontend}:${FRONTEND_IMAGE_TAG:-latest} # Use env vars with defaults
    container_name: odyssey-frontend
    restart: unless-stopped

  backend:
    # Removed build section
    image: ${REGISTRY_URL:-docker.io/rajmanghani}/${BACKEND_IMAGE_NAME:-raj-manghani-odyssey-backend}:${BACKEND_IMAGE_TAG:-latest} # Use env vars with defaults
    container_name: odyssey-backend
    environment:
      - DEPLOYMENT_MODE=docker
      - APP_ROOT_DIR=/app
    restart: unless-stopped

  proxy: # The Nginx Reverse Proxy service
    image: nginx:stable-alpine # Use standard nginx image
    container_name: nginx-proxy
    ports: # Add ports back since we removed network_mode: host
      - "80:80"
      - "443:443"
    # Removed network_mode: host
    extra_hosts: # Add mapping for host.docker.internal
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount the Nginx config from the host
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount volumes for certs and challenges (read-only for Nginx)
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_webroot:/var/www/certbot:ro
    depends_on: # depends_on might have limited effect with network_mode: host but good practice
      - frontend
      - backend
    restart: unless-stopped

  certbot: # Certbot Service for SSL Certificates
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      # Mount volumes for certs and challenges (read-write for Certbot)
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    # Entrypoint for auto-renewal
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Define named volumes at the TOP LEVEL
# Mark them as external and specify the existing volume names
volumes:
  certbot_certs:
    external: true
    name: raj-manghani-odyssey-resume_certbot_certs # Use the volume with the actual certs
  certbot_webroot:
    external: true
    name: app_certbot_webroot # Assuming this is the correct name, adjust if needed
