const degToRad = (degrees) => degrees * (Math.PI / 180);
const genericMoonTexture = '/textures/moon_map.jpg';
const sunSize = 3.0;

export const PLANET_DATA = {
    sun: { name: "Sun", size: sunSize, isEmissive: true, vitals: "Type: G-type Star | Diameter: ~1.4 million km | Temp: ~5,500°C (surface)", description: "The star at the center of our solar system, providing light and heat.", funFact: "The Sun accounts for about 99.86% of the total mass of the Solar System!", moons: [] },
    mercury: { name: "Mercury", size: 0.25, orbitRadius: 5, orbitSpeed: 0.25, yOffset: 0.1, tilt: degToRad(0.03), moons: [], vitals: "Type: Rocky Planet | Diameter: ~4,880 km | Temp: -173 to 427°C", description: "The smallest planet and closest to the Sun, with extreme temperature variations.", funFact: "A year on Mercury (one orbit) takes only 88 Earth days!" },
    venus:   { name: "Venus", size: 0.55, orbitRadius: 8, orbitSpeed: 0.18, yOffset: -0.2, tilt: degToRad(177.4), moons: [], vitals: "Type: Rocky Planet | Diameter: ~12,104 km | Temp: ~465°C (Hottest!)", description: "Similar in size to Earth but with a thick, toxic atmosphere and runaway greenhouse effect.", funFact: "Venus rotates backwards compared to most planets, and very slowly (a day is longer than its year)." },
    earth:   { name: "Earth", size: 0.6,  orbitRadius: 12, orbitSpeed: 0.15, yOffset: 0, tilt: degToRad(23.4), moons: [ { name: "Moon", size: 0.15, textureUrl: genericMoonTexture, orbitRadius: 1.0, orbitSpeed: 0.5, vitals: "Type: Natural Satellite | Diameter: ~3,474 km", description: "Earth's only natural satellite, influencing tides and stabilizing our planet's wobble.", funFact: "The Moon is slowly moving away from Earth at about 3.8 cm per year." } ], vitals: "Type: Rocky Planet | Diameter: ~12,742 km | Temp: Avg ~15°C", description: "Our home planet, the only known place with liquid water on the surface and life.", funFact: "Earth is not perfectly round; it bulges slightly at the equator." },
    mars:    { name: "Mars", size: 0.4, orbitRadius: 17, orbitSpeed: 0.12, yOffset: 0.3, tilt: degToRad(25.2), moons: [ { name: "Phobos", size: 0.05, textureUrl: genericMoonTexture, orbitRadius: 0.6, orbitSpeed: 0.7, vitals:"Moon", description:"Mars moon 1", funFact:"Fact 1"}, { name: "Deimos", size: 0.04, textureUrl: genericMoonTexture, orbitRadius: 0.8, orbitSpeed: 0.6, vitals:"Moon", description:"Mars moon 2", funFact:"Fact 2" } ], vitals: "Type: Rocky Planet | Diameter: ~6,779 km | Temp: -153 to 20°C", description: "The 'Red Planet', known for its iron oxide dust, polar ice caps, and potential for past life.", funFact: "Mars has the tallest volcano and the deepest, longest canyon in the solar system." },
    jupiter: { name: "Jupiter", size: 1.5, orbitRadius: 28, orbitSpeed: 0.06, yOffset: -0.4, tilt: degToRad(3.1), moons: [ { name: "Io", size: 0.3,  textureUrl: genericMoonTexture, orbitRadius: 2.5, orbitSpeed: 0.2, vitals:"Moon", description:"Jup moon 1", funFact:"Fact 1" }, { name: "Europa", size: 0.25, textureUrl: genericMoonTexture, orbitRadius: 3.2, orbitSpeed: 0.18, vitals:"Moon", description:"Jup moon 2", funFact:"Fact 2" }, { name: "Ganymede", size: 0.28, textureUrl: genericMoonTexture, orbitRadius: 4.0, orbitSpeed: 0.15, vitals:"Moon", description:"Jup moon 3", funFact:"Fact 3" } ], vitals: "Type: Gas Giant | Diameter: ~139,820 km | Temp: Avg ~-145°C (cloud tops)", description: "The largest planet in the solar system, a massive ball of gas with a Great Red Spot storm.", funFact: "Jupiter has the shortest day of all the planets, rotating once in just under 10 hours." },
    saturn:  { name: "Saturn", size: 1.2, orbitRadius: 40, orbitSpeed: 0.045, yOffset: 0.2, tilt: degToRad(26.7), moons: [ { name: "Titan", size: 0.25, textureUrl: genericMoonTexture, orbitRadius: 3.8, orbitSpeed: 0.1, vitals:"Moon", description:"Saturn moon 1", funFact:"Fact 1" }, { name: "Rhea", size: 0.2,  textureUrl: genericMoonTexture, orbitRadius: 4.8, orbitSpeed: 0.09, vitals:"Moon", description:"Saturn moon 2", funFact:"Fact 2" } ], vitals: "Type: Gas Giant | Diameter: ~116,460 km | Temp: Avg ~-178°C (cloud tops)", description: "Famous for its stunning, complex ring system made mostly of ice particles.", funFact: "Saturn is the least dense planet; it would float in water (if you could find a bathtub big enough!)." },
    uranus:  { name: "Uranus", size: 0.9, orbitRadius: 55, orbitSpeed: 0.03, yOffset: -0.1, tilt: degToRad(97.8), moons: [ { name: "Titania", size: 0.18, textureUrl: genericMoonTexture, orbitRadius: 1.8, orbitSpeed: 0.12, vitals:"Moon", description:"Uranus moon 1", funFact:"Fact 1" }, { name: "Oberon", size: 0.15, textureUrl: genericMoonTexture, orbitRadius: 2.5, orbitSpeed: 0.1, vitals:"Moon", description:"Uranus moon 2", funFact:"Fact 2" } ], vitals: "Type: Ice Giant | Diameter: ~50,724 km | Temp: Avg ~-216°C (cloud tops)", description: "An ice giant tilted on its side, possibly due to a massive collision long ago.", funFact: "Uranus appears blue-green because of methane gas in its atmosphere, which absorbs red light." },
    neptune: { name: "Neptune", size: 0.85, orbitRadius: 70, orbitSpeed: 0.025, yOffset: 0.15, tilt: degToRad(28.3), moons: [ { name: "Triton", size: 0.2, textureUrl: genericMoonTexture, orbitRadius: 2.0, orbitSpeed: 0.08, vitals:"Moon", description:"Neptune moon 1", funFact:"Fact 1" } ], vitals: "Type: Ice Giant | Diameter: ~49,244 km | Temp: Avg ~-214°C (cloud tops)", description: "A dark, cold ice giant with the strongest winds in the solar system.", funFact: "Neptune was the first planet located through mathematical prediction rather than direct observation." },
}; 