# ~/jenkins-setup/docker-compose.yml
services:
  jenkins:
    build:
      context: . # Build from the Dockerfile in the current directory (Dockerfile.jenkins)
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    restart: unless-stopped
    group_add:
      - "YOUR_GID_HERE" # <-- IMPORTANT: Replace with GID of 'docker' group on host VM (e.g., 999)
    # user: ... # Usually not needed if group_add works

volumes:
  jenkins_home: # Define the named volume for persistence
